/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "lcmtypes/h2sl_xml_string_t.h"

static int __h2sl_xml_string_t_hash_computed;
static int64_t __h2sl_xml_string_t_hash;

int64_t __h2sl_xml_string_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __h2sl_xml_string_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__h2sl_xml_string_t_get_hash;
    (void) cp;

    int64_t hash = 0xea923cbcf3bb4154LL
         + __int64_t_hash_recursive(&cp)
         + __string_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __h2sl_xml_string_t_get_hash(void)
{
    if (!__h2sl_xml_string_t_hash_computed) {
        __h2sl_xml_string_t_hash = __h2sl_xml_string_t_hash_recursive(NULL);
        __h2sl_xml_string_t_hash_computed = 1;
    }

    return __h2sl_xml_string_t_hash;
}

int __h2sl_xml_string_t_encode_array(void *buf, int offset, int maxlen, const h2sl_xml_string_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __string_encode_array(buf, offset + pos, maxlen - pos, &(p[element].xml), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int h2sl_xml_string_t_encode(void *buf, int offset, int maxlen, const h2sl_xml_string_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __h2sl_xml_string_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __h2sl_xml_string_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __h2sl_xml_string_t_encoded_array_size(const h2sl_xml_string_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int64_t_encoded_array_size(&(p[element].utime), 1);

        size += __string_encoded_array_size(&(p[element].xml), 1);

    }
    return size;
}

int h2sl_xml_string_t_encoded_size(const h2sl_xml_string_t *p)
{
    return 8 + __h2sl_xml_string_t_encoded_array_size(p, 1);
}

int __h2sl_xml_string_t_decode_array(const void *buf, int offset, int maxlen, h2sl_xml_string_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __string_decode_array(buf, offset + pos, maxlen - pos, &(p[element].xml), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __h2sl_xml_string_t_decode_array_cleanup(h2sl_xml_string_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_decode_array_cleanup(&(p[element].utime), 1);

        __string_decode_array_cleanup(&(p[element].xml), 1);

    }
    return 0;
}

int h2sl_xml_string_t_decode(const void *buf, int offset, int maxlen, h2sl_xml_string_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __h2sl_xml_string_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __h2sl_xml_string_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int h2sl_xml_string_t_decode_cleanup(h2sl_xml_string_t *p)
{
    return __h2sl_xml_string_t_decode_array_cleanup(p, 1);
}

int __h2sl_xml_string_t_clone_array(const h2sl_xml_string_t *p, h2sl_xml_string_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_clone_array(&(p[element].utime), &(q[element].utime), 1);

        __string_clone_array(&(p[element].xml), &(q[element].xml), 1);

    }
    return 0;
}

h2sl_xml_string_t *h2sl_xml_string_t_copy(const h2sl_xml_string_t *p)
{
    h2sl_xml_string_t *q = (h2sl_xml_string_t*) malloc(sizeof(h2sl_xml_string_t));
    __h2sl_xml_string_t_clone_array(p, q, 1);
    return q;
}

void h2sl_xml_string_t_destroy(h2sl_xml_string_t *p)
{
    __h2sl_xml_string_t_decode_array_cleanup(p, 1);
    free(p);
}

int h2sl_xml_string_t_publish(lcm_t *lc, const char *channel, const h2sl_xml_string_t *p)
{
      int max_data_size = h2sl_xml_string_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = h2sl_xml_string_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _h2sl_xml_string_t_subscription_t {
    h2sl_xml_string_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void h2sl_xml_string_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    h2sl_xml_string_t p;
    memset(&p, 0, sizeof(h2sl_xml_string_t));
    status = h2sl_xml_string_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding h2sl_xml_string_t!!!\n", status);
        return;
    }

    h2sl_xml_string_t_subscription_t *h = (h2sl_xml_string_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    h2sl_xml_string_t_decode_cleanup (&p);
}

h2sl_xml_string_t_subscription_t* h2sl_xml_string_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    h2sl_xml_string_t_handler_t f, void *userdata)
{
    h2sl_xml_string_t_subscription_t *n = (h2sl_xml_string_t_subscription_t*)
                       malloc(sizeof(h2sl_xml_string_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 h2sl_xml_string_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg h2sl_xml_string_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int h2sl_xml_string_t_subscription_set_queue_capacity (h2sl_xml_string_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int h2sl_xml_string_t_unsubscribe(lcm_t *lcm, h2sl_xml_string_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe h2sl_xml_string_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

