/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _h2sl_xml_string_t_h
#define _h2sl_xml_string_t_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _h2sl_xml_string_t h2sl_xml_string_t;
struct _h2sl_xml_string_t
{
    int64_t    utime;
    char*      xml;
};

h2sl_xml_string_t   *h2sl_xml_string_t_copy(const h2sl_xml_string_t *p);
void h2sl_xml_string_t_destroy(h2sl_xml_string_t *p);

typedef struct _h2sl_xml_string_t_subscription_t h2sl_xml_string_t_subscription_t;
typedef void(*h2sl_xml_string_t_handler_t)(const lcm_recv_buf_t *rbuf,
             const char *channel, const h2sl_xml_string_t *msg, void *user);

int h2sl_xml_string_t_publish(lcm_t *lcm, const char *channel, const h2sl_xml_string_t *p);
h2sl_xml_string_t_subscription_t* h2sl_xml_string_t_subscribe(lcm_t *lcm, const char *channel, h2sl_xml_string_t_handler_t f, void *userdata);
int h2sl_xml_string_t_unsubscribe(lcm_t *lcm, h2sl_xml_string_t_subscription_t* hid);
int h2sl_xml_string_t_subscription_set_queue_capacity(h2sl_xml_string_t_subscription_t* subs,
                              int num_messages);


int  h2sl_xml_string_t_encode(void *buf, int offset, int maxlen, const h2sl_xml_string_t *p);
int  h2sl_xml_string_t_decode(const void *buf, int offset, int maxlen, h2sl_xml_string_t *p);
int  h2sl_xml_string_t_decode_cleanup(h2sl_xml_string_t *p);
int  h2sl_xml_string_t_encoded_size(const h2sl_xml_string_t *p);

// LCM support functions. Users should not call these
int64_t __h2sl_xml_string_t_get_hash(void);
int64_t __h2sl_xml_string_t_hash_recursive(const __lcm_hash_ptr *p);
int     __h2sl_xml_string_t_encode_array(void *buf, int offset, int maxlen, const h2sl_xml_string_t *p, int elements);
int     __h2sl_xml_string_t_decode_array(const void *buf, int offset, int maxlen, h2sl_xml_string_t *p, int elements);
int     __h2sl_xml_string_t_decode_array_cleanup(h2sl_xml_string_t *p, int elements);
int     __h2sl_xml_string_t_encoded_array_size(const h2sl_xml_string_t *p, int elements);
int     __h2sl_xml_string_t_clone_array(const h2sl_xml_string_t *p, h2sl_xml_string_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
