"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class xml_string_t(object):
    __slots__ = ["utime", "xml"]

    def __init__(self):
        self.utime = 0
        self.xml = ""

    def encode(self):
        buf = BytesIO()
        buf.write(xml_string_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        __xml_encoded = self.xml.encode('utf-8')
        buf.write(struct.pack('>I', len(__xml_encoded)+1))
        buf.write(__xml_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != xml_string_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return xml_string_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = xml_string_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        __xml_len = struct.unpack('>I', buf.read(4))[0]
        self.xml = buf.read(__xml_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if xml_string_t in parents: return 0
        tmphash = (0xea923cbcf3bb4154) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if xml_string_t._packed_fingerprint is None:
            xml_string_t._packed_fingerprint = struct.pack(">Q", xml_string_t._get_hash_recursive([]))
        return xml_string_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

